;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        dabbrev-expand
        dired-next-line
        end-of-buffer
        hungry-delete-backward
        ido-switch-buffer
        isearch-backward-regexp
        kill-region
        org-beginning-of-line
        org-delete-char
        org-metaleft
        org-metaright
        org-self-insert-command
        scroll-n-lines-ahead
        sgml-slash
        split-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-forward-regexp
        isearch-printing-char
        yas/expand
        ))
